project:
  type: book
  output-dir: docs
lang: es

book: 
  title: "Estadística a vista de pájaro"
  subtitle: "Estoy haciendo pruebas"
  date: today
  date-format: medium
  author: "Roberto Behar / Pere Grima / Lluís Marco-Almagro"
  sidebar:
      collapse-level: 0
  cover-image: cover.jpg
  site-url: https://peregrima.github.io/VistadePajaro/

  chapters:
    - index.qmd
    - 01_Prologo.qmd
    - 10_INTRODUCCION.qmd
     
    - part: 20_DESCRIPTIVA.qmd                  # I ESTADÍSTICA DESCRIPTIVA
      chapters: 
        - 21_sintesisNumerica.qmd               # 2. Síntesis numérica de datos
        - 22_Graficos.qmd                       # 3. Representaciones gráficas
        
    - part: 30_VARIABILIDAD.qmd                 # II DESCRIBIR LO ALEATORIO
      chapters:
        - 31_variablesAleatorias.qmd            # 4. Variables aleatorias    
        - 32_distribucionesProbabilidad.qmd     # 5. Distribuciones de probabilidad
        
    - part: 40_MUESTRA_POBLACION.qmd            # III DE LA MUESTRA A LA POBLACIÓN
      chapters: 
        - 41_muestreo.qmd                       # 6. Muestreo. Encuestas
        - 42_estimacion.qmd                     # 7. Estimación de características de la población
        
    - part: 50_SIGNIFICATIVO.qmd                # IV ESTADÍSTICAMENTE SIGNIFICATIVO
      chapters: 
        - 51_contrasteHipotesis.qmd             # 8. Contraste de hipótesis
        - 52_algunosTest.qmd                    # 9. Algunos test clásicos

    - part: 60_CORRELACION.qmd                  # V CORRELACIÓN Y REGRESIÓN
      chapters: 
        - 61_relacionLineal.qmd                 # 10. Medidas de relación lineal
        - 62_regreSimple.qmd                    # 11. Regresión simple
        - 63_regreMultiple.qmd                  # 12. Regresión múltiple
        
    - part: EPILOGO.qmd                         # EPÍLOGO
      
    - part: ORIGEN_DATOS.qmd                    # Origen de los datos
             
    - references.qmd                            # Referencias

# Referencias
biblio-title: "Referencias"
link-citations: true
link-bibliography: true
cite-method: citeproc         # Solo PDF
biblio-style: 'authoryear'    # Solo PDF
citations-hover: true         # Solo HTML
bibliography: references.bib 

# Fuentes ----------------------------
mainfont: Calibri
monofont: Verdana
mathfont: CambriaMath
fontfamily: baskervald    # -> Solo en PDF
fontsize: 13pt
# systemfonts::system_fonts(): Lista de fuentes disponibles en el ordenador.


format:
  html:
    theme: cosmo
    code-fold: true
    css: styles.css
    header-includes:
      <script src="https://kit.fontawesome.com/98a945d90a.js" crossorigin="anonymous"></script>
  pdf:
    documentclass: scrreprt

editor: visual

